apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-tester
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-tester
spec:
  selector:
    app: gatekeeper-tester
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    # Capture webhook port — the kube-apiserver calls this over HTTPS
    - name: capture
      port: 8443
      targetPort: 8443
